/**
 * Types for the IssueReporter agent sub-modules
 */

import { GitHubConfig } from '../../models/Config';

/**
 * GitHub API rate limit information
 */
export interface RateLimitInfo {
  limit: number;
  used: number;
  remaining: number;
  reset: Date;
}

/**
 * Issue fingerprint for deduplication
 */
export interface IssueFingerprint {
  scenarioId: string;
  errorMessage: string;
  stackTraceHash?: string;
  category?: string;
  hash: string;
}

/**
 * GitHub issue creation options
 */
export interface CreateIssueOptions {
  title: string;
  body: string;
  labels?: string[];
  assignees?: string[];
  milestone?: number;
  projects?: number[];
}

/**
 * GitHub issue update options
 */
export interface UpdateIssueOptions {
  title?: string;
  body?: string;
  state?: 'open' | 'closed';
  labels?: string[];
  assignees?: string[];
  milestone?: number | null;
}

/**
 * GitHub pull request creation options
 */
export interface CreatePullRequestOptions {
  title: string;
  body: string;
  head: string;
  base: string;
  draft?: boolean;
  maintainer_can_modify?: boolean;
}

/**
 * Issue template variables
 */
export interface IssueTemplateVars {
  scenarioId: string;
  scenarioName: string;
  failureMessage: string;
  stackTrace?: string;
  timestamp: string;
  environment: Record<string, any>;
  screenshots?: string[];
  logs?: string[];
  reproductionSteps: string[];
  systemInfo: Record<string, any>;
  priority: string;
  category?: string;
}

/**
 * System information for issues
 */
export interface SystemInfo {
  platform: string;
  arch: string;
  nodeVersion: string;
  electronVersion?: string;
  timestamp: string;
  workingDirectory: string;
  environment: Record<string, string>;
}

/**
 * Issue Reporter agent configuration
 */
export interface IssueReporterConfig extends GitHubConfig {
  /** GitHub API base URL (for Enterprise) */
  baseUrl?: string;
  /** Request timeout in milliseconds */
  timeout?: number;
  /** Rate limit buffer (requests to keep in reserve) */
  rateLimitBuffer?: number;
  /** Custom issue templates directory */
  templatesDir?: string;
  /** Screenshot storage configuration */
  screenshotStorage?: 'embed' | 'link' | 'attach';
  /** Maximum issue body length */
  maxBodyLength?: number;
  /** Issue deduplication enabled */
  enableDeduplication?: boolean;
  /** Days to look back for duplicate issues */
  deduplicationLookbackDays?: number;
}

/**
 * Default configuration values
 */
export const DEFAULT_CONFIG: Partial<IssueReporterConfig> = {
  timeout: 30000,
  rateLimitBuffer: 100,
  screenshotStorage: 'link',
  maxBodyLength: 65536,
  enableDeduplication: true,
  deduplicationLookbackDays: 30,
  issueTitleTemplate: '[TEST FAILURE] {{scenarioName}} - {{failureMessage}}',
  issueBodyTemplate: `## Test Failure Report

**Scenario:** {{scenarioName}} ({{scenarioId}})
**Failure Time:** {{timestamp}}
**Priority:** {{priority}}

### Error Details
\`\`\`
{{failureMessage}}
\`\`\`

{{#stackTrace}}
### Stack Trace
\`\`\`
{{stackTrace}}
\`\`\`
{{/stackTrace}}

### Reproduction Steps
{{#reproductionSteps}}
{{#each this}}
{{@index}}. {{this}}
{{/each}}
{{/reproductionSteps}}

### Environment Information
- **Platform:** {{systemInfo.platform}} {{systemInfo.arch}}
- **Node Version:** {{systemInfo.nodeVersion}}
{{#systemInfo.electronVersion}}
- **Electron Version:** {{systemInfo.electronVersion}}
{{/systemInfo.electronVersion}}
- **Working Directory:** {{systemInfo.workingDirectory}}

{{#screenshots}}
### Screenshots
{{#each this}}
- ![Screenshot]({{this}})
{{/each}}
{{/screenshots}}

{{#logs}}
### Relevant Logs
\`\`\`
{{#each this}}
{{this}}
{{/each}}
\`\`\`
{{/logs}}

---
*This issue was automatically generated by the Agentic Testing System*`,
  issueLabels: ['bug', 'test-failure', 'automated'],
  autoAssignUsers: [],
  createIssuesOnFailure: true,
  createPullRequestsForFixes: false
};
